version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: restman-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: restman
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/restman.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      restman-network:
        aliases:
          - localhost
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    build: .
    container_name: restman-webapp
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - restman-network

networks:
  restman-network:
    driver: bridge

volumes:
  mysql-data:
